networks:
  yamata-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  nginx_logs:

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.29.0
    container_name: yamata-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_logs:/var/log/nginx
      - ./docker/nginx/sites-available/generated:/etc/nginx/sites-available:ro
      - ./docker/nginx/sites-available/generated/yamata.conf:/etc/nginx/sites-enabled/yamata.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./docker/nginx/security.conf:/etc/nginx/security.conf:ro
      - ./docker/nginx/gzip.conf:/etc/nginx/gzip.conf:ro
    networks:
      yamata-network:
        ipv4_address: 172.20.0.20
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run 