// Package dto contains Data Transfer Objects for API request and response structures
package dto

// ChargeWalletRequest represents the request to charge a wallet
type ChargeWalletRequest struct {
	Amount     uint64 `json:"amount" validate:"required,min=10000,max=1000000000"` // Amount in Tomans (minimum 10000, maximum 1000000000)
	CustomerID uint   `json:"-"`
}

// ChargeWalletResponse represents the response after successfully charging a wallet
type ChargeWalletResponse struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
	Token   string `json:"token"`
}

// PaymentCallbackRequest represents the callback data from Atipay after payment completion
type PaymentCallbackRequest struct {
	State             string `json:"state"`             // Transaction status (1=CanceledByUser, 2=OK, 3=Failed, etc.)
	Status            string `json:"status"`            // Payment status code
	ReferenceNumber   string `json:"referenceNumber"`   // Unique digital receipt (alphanumeric)
	ReservationNumber string `json:"reservationNumber"` // The unique ID originally sent by merchant (our invoice number)
	TerminalID        string `json:"terminalId"`        // Terminal number used for payment
	TraceNumber       string `json:"traceNumber"`       // Tracking number generated by payment gateway
	MaskedPAN         string `json:"maskedPan"`         // Masked card number used for payment
	RRN               string `json:"rrn"`               // Transaction reference number
}
