// Package dto contains Data Transfer Objects for API request and response structures
package dto

import "time"

// GetPaymentTokenRequest represents the request to get a payment token from Atipay
type GetPaymentTokenRequest struct {
	// Payment details
	Amount      uint64 `json:"amount" validate:"required,min=10000"`          // Amount in Tomans (minimum 10000)
	Description string `json:"description" validate:"required,max=255"`       // Transaction description
	RedirectURL string `json:"redirect_url" validate:"required,url"`          // URL to redirect after payment
	CellNumber  string `json:"cell_number" validate:"required,mobile_format"` // Buyer's mobile number

	// Internal fields (not sent to Atipay, used for our system)
	CustomerID uint `json:"customer_id" validate:"required"` // Customer ID for wallet association
}

// GetPaymentTokenResponse represents the response after successfully getting a payment token
type GetPaymentTokenResponse struct {
	Message          string    `json:"message"`
	PaymentRequestID uint      `json:"payment_request_id"`
	UUID             string    `json:"uuid"`
	AtipayToken      string    `json:"atipay_token"` // Token from Atipay for redirect
	RedirectURL      string    `json:"redirect_url"` // URL to redirect user to Atipay
	Amount           uint64    `json:"amount"`       // Amount in Rials
	Description      string    `json:"description"`  // Transaction description
	ExpiresAt        time.Time `json:"expires_at"`   // When the payment request expires
	Status           string    `json:"status"`       // Current status of payment request
}

// PaymentCallbackRequest represents the callback data from Atipay after payment completion
type PaymentCallbackRequest struct {
	State             string `json:"state"`             // Transaction status (1=CanceledByUser, 2=OK, 3=Failed, etc.)
	Status            string `json:"status"`            // Payment status code
	ReferenceNumber   string `json:"referenceNumber"`   // Unique digital receipt (alphanumeric)
	ReservationNumber string `json:"reservationNumber"` // The unique ID originally sent by merchant (our invoice number)
	TerminalID        string `json:"terminalId"`        // Terminal number used for payment
	TraceNumber       string `json:"traceNumber"`       // Tracking number generated by payment gateway
	MaskedPAN         string `json:"maskedPan"`         // Masked card number used for payment
	RRN               string `json:"rrn"`               // Transaction reference number
}

// PaymentCallbackResponse represents the response to Atipay callback
type PaymentCallbackResponse struct {
	Message          string `json:"message"`
	Success          bool   `json:"success"`
	PaymentRequestID uint   `json:"payment_request_id,omitempty"`
	Status           string `json:"status,omitempty"`
}

// VerifyPaymentRequest represents the request to verify payment with Atipay
type VerifyPaymentRequest struct {
	ReferenceNumber string `json:"reference_number" validate:"required"` // Value received from Atipay callback
}

// VerifyPaymentResponse represents the response after payment verification
type VerifyPaymentResponse struct {
	Message         string    `json:"message"`
	Success         bool      `json:"success"`
	Amount          uint64    `json:"amount"`           // Verified amount from Atipay
	ReferenceNumber string    `json:"reference_number"` // Atipay reference number
	VerifiedAt      time.Time `json:"verified_at"`      // When verification was completed
	Status          string    `json:"status"`           // Final payment status
}

// PaymentStatus represents the status of a payment request
type PaymentStatus string

const (
	PaymentStatusCreated   PaymentStatus = "created"   // Payment request created, waiting for Atipay token
	PaymentStatusTokenized PaymentStatus = "tokenized" // Atipay token received, waiting for user payment
	PaymentStatusPending   PaymentStatus = "pending"   // User redirected to Atipay, payment in progress
	PaymentStatusCompleted PaymentStatus = "completed" // Payment completed successfully
	PaymentStatusFailed    PaymentStatus = "failed"    // Payment failed
	PaymentStatusCancelled PaymentStatus = "cancelled" // User cancelled payment
	PaymentStatusExpired   PaymentStatus = "expired"   // Payment request expired
	PaymentStatusRefunded  PaymentStatus = "refunded"  // Payment was refunded
)

// PaymentError represents payment-related errors
type PaymentError struct {
	Code        string `json:"code"`
	Message     string `json:"message"`
	Description string `json:"description,omitempty"`
}
