package models

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// CryptoPlatform represents external crypto payment platform/provider (e.g., bithide)
type CryptoPlatform string

const (
	CryptoPlatformBithide CryptoPlatform = "bithide"
)

// CryptoCurrency represents supported crypto assets for deposit
type CryptoCurrency string

const (
	CryptoCurrencyETH  CryptoCurrency = "ETH"
	CryptoCurrencyDOGE CryptoCurrency = "DOGE"
	CryptoCurrencyXRP  CryptoCurrency = "XRP"
	CryptoCurrencyBNB  CryptoCurrency = "BNB"
)

// CryptoPaymentStatus represents lifecycle for crypto payment requests
type CryptoPaymentStatus string

const (
	// created -> address_provisioned -> pending -> confirmed -> credited
	CryptoPaymentStatusCreated            CryptoPaymentStatus = "created"
	CryptoPaymentStatusAddressProvisioned CryptoPaymentStatus = "address_provisioned"
	CryptoPaymentStatusPending            CryptoPaymentStatus = "pending"
	CryptoPaymentStatusConfirmed          CryptoPaymentStatus = "confirmed"
	CryptoPaymentStatusCredited           CryptoPaymentStatus = "credited"
	CryptoPaymentStatusFailed             CryptoPaymentStatus = "failed"
	CryptoPaymentStatusCancelled          CryptoPaymentStatus = "cancelled"
	CryptoPaymentStatusExpired            CryptoPaymentStatus = "expired"
)

// CryptoPaymentRequest captures a user's intent to charge wallet via crypto deposit
// Amounts:
//   - FiatAmountToman is requested total in Tomans (to be credited as Toman/currency into wallet)
//   - ExpectedCoinAmount is the coin amount quoted at request time (precision stored as numeric via string)
type CryptoPaymentRequest struct {
	ID            uint      `gorm:"primaryKey;autoIncrement" json:"id"`
	UUID          uuid.UUID `gorm:"type:uuid;uniqueIndex;not null;default:gen_random_uuid()" json:"uuid"`
	CorrelationID uuid.UUID `gorm:"type:uuid;index;not null" json:"correlation_id"`

	CustomerID uint `gorm:"not null;index" json:"customer_id"`
	WalletID   uint `gorm:"not null;index" json:"wallet_id"`

	// Requested amounts
	FiatAmountToman    uint64         `gorm:"not null" json:"fiat_amount_toman"`
	FiatCurrency       string         `gorm:"type:varchar(3);not null;default:'TMN'" json:"fiat_currency"`
	Coin               CryptoCurrency `gorm:"type:varchar(16);not null;index" json:"coin"`
	Network            string         `gorm:"type:varchar(64);not null;index" json:"network"`
	Platform           CryptoPlatform `gorm:"type:varchar(64);not null;index" json:"platform"`
	ExpectedCoinAmount string         `gorm:"type:numeric(38,18);not null" json:"expected_coin_amount"`
	ExchangeRate       string         `gorm:"type:numeric(38,18);not null" json:"exchange_rate"` // coin per Toman or vice versa
	RateSource         string         `gorm:"type:varchar(128)" json:"rate_source"`

	// Deposit details provisioned by provider or generated by us
	DepositAddress string `gorm:"type:varchar(255);index" json:"deposit_address"`
	DepositMemo    string `gorm:"type:varchar(255);index" json:"deposit_memo"` // destination tag/memo for chains like XRP

	// Provider identifiers and state
	ProviderRequestID string `gorm:"type:varchar(255);index" json:"provider_request_id"`

	Status       CryptoPaymentStatus `gorm:"type:varchar(32);not null;default:'created';index" json:"status"`
	StatusReason string              `gorm:"type:text" json:"status_reason"`

	// Timestamps and expiry
	ExpiresAt   *time.Time `gorm:"index" json:"expires_at"`
	DetectedAt  *time.Time `gorm:"index" json:"detected_at"`
	ConfirmedAt *time.Time `gorm:"index" json:"confirmed_at"`
	CreditedAt  *time.Time `gorm:"index" json:"credited_at"`

	// Metadata
	Metadata  json.RawMessage `gorm:"type:jsonb;default:'{}'" json:"metadata"`
	CreatedAt time.Time       `gorm:"not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time       `gorm:"not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt  `gorm:"index" json:"deleted_at,omitempty"`

	// Relations
	Customer Customer `gorm:"foreignKey:CustomerID;constraint:OnDelete:CASCADE" json:"customer,omitempty"`
	Wallet   Wallet   `gorm:"foreignKey:WalletID;constraint:OnDelete:CASCADE" json:"wallet,omitempty"`
}

// BeforeCreate ensures UUID and CorrelationID are set
func (cpr *CryptoPaymentRequest) BeforeCreate(tx *gorm.DB) error {
	if cpr.UUID == uuid.Nil {
		cpr.UUID = uuid.New()
	}
	if cpr.CorrelationID == uuid.Nil {
		cpr.CorrelationID = uuid.New()
	}
	return nil
}

// IsFinal returns true if the request is in a terminal state
func (cpr *CryptoPaymentRequest) IsFinal() bool {
	return cpr.Status == CryptoPaymentStatusCredited ||
		cpr.Status == CryptoPaymentStatusFailed ||
		cpr.Status == CryptoPaymentStatusCancelled ||
		cpr.Status == CryptoPaymentStatusExpired
}

// CryptoPaymentRequestFilter provides query criteria
type CryptoPaymentRequestFilter struct {
	ID                *uint                `json:"id,omitempty"`
	UUID              *uuid.UUID           `json:"uuid,omitempty"`
	CorrelationID     *uuid.UUID           `json:"correlation_id,omitempty"`
	CustomerID        *uint                `json:"customer_id,omitempty"`
	WalletID          *uint                `json:"wallet_id,omitempty"`
	Coin              *CryptoCurrency      `json:"coin,omitempty"`
	Network           *string              `json:"network,omitempty"`
	Platform          *CryptoPlatform      `json:"platform,omitempty"`
	Status            *CryptoPaymentStatus `json:"status,omitempty"`
	DepositAddress    *string              `json:"deposit_address,omitempty"`
	DepositMemo       *string              `json:"deposit_memo,omitempty"`
	ProviderRequestID *string              `json:"provider_request_id,omitempty"`
	CreatedAfter      *time.Time           `json:"created_after,omitempty"`
	CreatedBefore     *time.Time           `json:"created_before,omitempty"`
	ExpiresAfter      *time.Time           `json:"expires_after,omitempty"`
	ExpiresBefore     *time.Time           `json:"expires_before,omitempty"`
}

// CryptoDeposit represents an on-chain deposit event possibly linked to a payment request
type CryptoDeposit struct {
	ID            uint      `gorm:"primaryKey;autoIncrement" json:"id"`
	UUID          uuid.UUID `gorm:"type:uuid;uniqueIndex;not null;default:gen_random_uuid()" json:"uuid"`
	CorrelationID uuid.UUID `gorm:"type:uuid;index;not null" json:"correlation_id"`

	CryptoPaymentRequestID *uint `gorm:"index" json:"crypto_payment_request_id"`
	CustomerID             uint  `gorm:"not null;index" json:"customer_id"`
	WalletID               uint  `gorm:"not null;index" json:"wallet_id"`

	Coin     CryptoCurrency `gorm:"type:varchar(16);not null;index" json:"coin"`
	Network  string         `gorm:"type:varchar(64);not null;index" json:"network"`
	Platform CryptoPlatform `gorm:"type:varchar(64);not null;index" json:"platform"`

	TxHash         string `gorm:"type:varchar(255);uniqueIndex" json:"tx_hash"`
	FromAddress    string `gorm:"type:varchar(255);index" json:"from_address"`
	ToAddress      string `gorm:"type:varchar(255);index" json:"to_address"`
	DestinationTag string `gorm:"type:varchar(255);index" json:"destination_tag"`

	AmountCoin            string `gorm:"type:numeric(38,18);not null" json:"amount_coin"`
	Confirmations         int    `gorm:"not null;default:0" json:"confirmations"`
	RequiredConfirmations int    `gorm:"not null;default:0" json:"required_confirmations"`
	BlockHeight           *int64 `json:"block_height"`

	DetectedAt  *time.Time `gorm:"index" json:"detected_at"`
	ConfirmedAt *time.Time `gorm:"index" json:"confirmed_at"`
	CreditedAt  *time.Time `gorm:"index" json:"credited_at"`

	Status   string          `gorm:"type:varchar(32);not null;default:'detected';index" json:"status"` // detected|confirmed|credited|ignored
	Metadata json.RawMessage `gorm:"type:jsonb;default:'{}'" json:"metadata"`

	CreatedAt time.Time      `gorm:"not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"deleted_at,omitempty"`
}

// BeforeCreate ensures UUID and CorrelationID are set
func (cd *CryptoDeposit) BeforeCreate(tx *gorm.DB) error {
	if cd.UUID == uuid.Nil {
		cd.UUID = uuid.New()
	}
	if cd.CorrelationID == uuid.Nil {
		cd.CorrelationID = uuid.New()
	}
	return nil
}

// CryptoDepositFilter provides query criteria for deposits
type CryptoDepositFilter struct {
	ID                     *uint           `json:"id,omitempty"`
	UUID                   *uuid.UUID      `json:"uuid,omitempty"`
	CorrelationID          *uuid.UUID      `json:"correlation_id,omitempty"`
	CryptoPaymentRequestID *uint           `json:"crypto_payment_request_id,omitempty"`
	CustomerID             *uint           `json:"customer_id,omitempty"`
	WalletID               *uint           `json:"wallet_id,omitempty"`
	Coin                   *CryptoCurrency `json:"coin,omitempty"`
	Network                *string         `json:"network,omitempty"`
	Platform               *CryptoPlatform `json:"platform,omitempty"`
	TxHash                 *string         `json:"tx_hash,omitempty"`
	ToAddress              *string         `json:"to_address,omitempty"`
	Status                 *string         `json:"status,omitempty"`
	CreatedAfter           *time.Time      `json:"created_after,omitempty"`
	CreatedBefore          *time.Time      `json:"created_before,omitempty"`
	ConfirmedOnly          *bool           `json:"confirmed_only,omitempty"`
}
